[tools]
# Стабильная версия Ruby на которой Fastlane работает гарантированно
ruby = "3.3"

tuist = "4.21.0"
swiftlint = "latest"

[env]
# Исправляем вечные ошибки кодировки которые валят Fastlane
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"

[tasks]
install = "tuist install"
i = "tuist install"
generate = "tuist generate"
g = "tuist generate"
edit = "tuist edit"
e = "tuist edit"
clean = "tuist clean"
fetch = "tuist fetch"
test = "tuist test"
install-fastlane = "gem install fastlane --version 2.238.0 --no-document"

[tasks.lint]
depends = ["install-fastlane"]
run = "fastlane lint"

[tasks.check]
depends = ["install-fastlane"]
run = "fastlane check"
