default_platform(:ios)

platform :ios do
  
  desc "Проверка стиля кода"
  lane :lint do
    Dir.chdir("..") do
      # --strict заставит билд упасть, если есть ошибки стиля
      sh("swiftlint lint Projects --config .swiftlint.yml --strict")
    end
  end

  desc "Полная подготовка проекта и запуск тестов"
  lane :check do
    # 1. Запуск линтера
    lint
    
    # 2. Работа с Tuist
    Dir.chdir("..") do     
      sh("tuist install")
      sh("tuist generate --no-open")
      
      # Автоматический поиск первого доступного iPhone на сервере
      device_name = sh("xcrun simctl list devices available | awk -F '[()]' '/iPhone/ { print $1; exit }' | xargs").strip

      if device_name.empty?
        UI.user_error!("No available iPhone simulator found")
      end

      UI.message("🚀 Запуск тестов на устройстве: #{device_name}")
      
      # Запуск тестов через Tuist на найденном симуляторе
      sh("tuist test --device '#{device_name}'")
    end    
  end
end
