name: CI

on:
  push:
    branches: [ "main", "alrzi-patch-1" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show available Xcode
        run: |
          ls -d /Applications/Xcode_*.app
          xcodebuild -version

      - name: Select Highest Xcode
        run: |
          # Пытаемся найти 16.2 явно, если нет - берем самый старший
          if [ -d "/Applications/Xcode_16.2.app" ]; then
            sudo xcode-select -s /Applications/Xcode_16.2.app
          else
            LATEST_XCODE=$(ls -d /Applications/Xcode_*.app | sort -V | tail -1)
            sudo xcode-select -s "$LATEST_XCODE"
          fi
          echo "Selected Xcode: $(xcode-select -p)"
          swift --version

      - name: Install tools (mise)
        uses: jdx/mise-action@v2

      - name: Run CI
        run: mise run check
